// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9H1On9FbALuriZbWWtM-lHPd9t1-Cpzs',
    appId: '1:472454734513:web:96df0394af6a20f8497890',
    messagingSenderId: '472454734513',
    projectId: 'momento-59807',
    authDomain: 'momento-59807.firebaseapp.com',
    storageBucket: 'momento-59807.firebasestorage.app',
    measurementId: 'G-DRWL5SZWZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJbeSG9JODsM6Yj62wfoLdOOf4CXRsC2I',
    appId: '1:472454734513:android:6870fa090204f492497890',
    messagingSenderId: '472454734513',
    projectId: 'momento-59807',
    storageBucket: 'momento-59807.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9H1On9FbALuriZbWWtM-lHPd9t1-Cpzs',
    appId: '1:472454734513:web:48e8ccf1828e4dc0497890',
    messagingSenderId: '472454734513',
    projectId: 'momento-59807',
    authDomain: 'momento-59807.firebaseapp.com',
    storageBucket: 'momento-59807.firebasestorage.app',
    measurementId: 'G-5EGT7FGTVR',
  );
}
